### ISSUE TITLE
Keyv v5 

### ISSUE THREAD

**Issue by jaredwray** [goto-bus-stop/keyv-firestore#51]
Hi! 👋 

Hope you are doing great. I noticed you havent upgraded to the latest Keyv. Do you plan too? Let me know if you need help.

**Comment by goto-bus-stop** [comment]
Thanks for the notification! If the upgrade is easy enough I'll just add it to the range of supported versions of this package :) At first glance it looks like that should be no problem.

I noticed one blocker for my test script. With the new package.json `exports` field, only the entry point is exported. I use the package.json to check the version:
https://github.com/goto-bus-stop/keyv-firestore/blob/d7e6c2f4ea3ba696c1857e0ec92cffd5bcb4d73d/test.js#L15
So it would be helpful if keyv could add this to its package.jsons:
```json
"exports": {
  "./package.json": "./package.json"
}
```
I wish it was the default for node packages, but alas every package has to write it out manually.

**Comment by jaredwray** [comment]
We usually do not do this due to security concerns.
________________________________

**Comment by goto-bus-stop** [comment]
How so? Looking at it again, I can work around it by telling the test suite about the version in a different way (by having the github action provide it as an env variable), but I'm surprised to hear this. I consider finding the actually-installed package version at runtime an important feature of node packages, especially for peer dependencies.

**Comment by goto-bus-stop** [comment]
2.1.0 is out with v5 support 😄
